[workspace]
changelog_update = true
git_tag_enable = true
git_release_enable = true
pr_labels = ["release"]
pr_name = "chore: release{% if package %} {{ package }}{% endif %}"

[[package]]
name = "groupoid"
changelog_path = "./CHANGELOG.md"
changelog_include = ["groupoid_macros"]

[[package]]
name = "groupoid_macros"
changelog_update = false
git_release_enable = false
