[workspace]
changelog_update = true
git_tag_enable = true
git_release_enable = true
pr_labels = ["release"]
pr_name = "chore: release{% if package %} {{ package }}{% endif %}"

[[package]]
name = "typestate-groups"
changelog_path = "./CHANGELOG.md"
changelog_include = ["typestate-groups-macros"]

[[package]]
name = "typestate-groups-macros"
changelog_update = false
git_release_enable = false
