pub use groupoid_macros::*;

/// A type that represents a state of an object.
pub trait State {}

/// A type that has a state.
pub trait WithState {
    type State: State;
}

/// A type that captures a specific implementation of a [`group_trait`]
pub trait Group {}

// TODO: Maybe use in the future
// pub trait GroupMarker {
// type Marker: Group;
// }

// TODO: possible bugs may occur because of this, should ensure that the
// SIZE and the ALIGN are matching.

/// A group that it's type has a known compiletime size.
pub trait SizedGroup<const SIZE: usize>: Group {}

/// A group whose type has a known compile time alignment.
#[diagnostic::on_unimplemented(
    message = "the group `{Self}` is not {ALIGN} byte aligned"
)]
pub trait AlignedGroup<const ALIGN: usize>: Group {}

/// A type that contains a group state, which implements [`SizedGroup`] and
/// [`AlignedGroup`].
pub trait SizedWithState<const SIZE: usize, const ALIGN: usize>:
    WithState + Sized
{
}

/// Marks that `Self` can have the [`State`] `To` plugged in, in place of
/// its own, without changing its layout.
///
/// # Safety
///
/// Implementing this trait is an assertion that `Self` and `Target` are
/// actually the same underlying container, laid out identically, same
/// field offsets, same size, same alignment.
#[diagnostic::on_unimplemented(
    message = "`{Self}` cannot be transmuted into state `{To}`",
    note = "`TransmutableState` is generated by \
            `#[typestate(unsafe_transmute = true)]`, and only between \
            two states of the *same* struct whose values agree on size \
            and alignment",
    note = "a by-value transition does not need the flag or a shared \
            layout: see the `restate_with` method every `#[typestate]` \
            generates"
)]
pub unsafe trait TransmutableState<
    To: State,
    const SIZE: usize,
    const ALIGN: usize,
>: SizedWithState<SIZE, ALIGN>
{
    /// `Self` with `To` as its state and every other generic unchanged.
    type Target: SizedWithState<SIZE, ALIGN> + WithState<State = To>;

    /// Compile time proof that `Self` and [`Target`](Self::Target) really
    /// do share a layout
    ///
    /// ```ignore
    /// const _: () = <Wrap<Small> as TransmutableState<Big, 4, 4>>::LAYOUT_CHECK;
    /// ```
    const LAYOUT_CHECK: () = {
        assert!(
            core::mem::size_of::<Self>()
                == core::mem::size_of::<Self::Target>(),
            "`Self` and `Target` does not have the same size"
        );
        assert!(
            core::mem::align_of::<Self>()
                == core::mem::align_of::<Self::Target>(),
            "`Self` and `Target` does not have the same alignment"
        );
    };
}

/// Bit-reinterpretation transitions between [`State`]s of the same
/// [`WithState`] container type.
///
/// Each method takes only the target *state*; the container it lands in is
/// [`TransmutableState::Target`], which is `Self` with that state swapped
/// in:
///
/// ```ignore
/// #[typestate(state = S, unsafe_transmute = true)]
/// struct Wrap<S: Meta> { value: S::Value }
///
/// let big = unsafe { small.transmute_state::<Big>() }; // Wrap<Small> -> Wrap<Big>
/// ```
///
/// `SIZE` and `ALIGN` are the layout key both states must agree on (see
/// [`SizedWithState`]).
pub trait TransmuteState<const SIZE: usize, const ALIGN: usize>:
    WithState + Sized
{
    /// Bit-reinterprets `self` as the same container type with the
    /// [`State`] `To` plugged in.
    ///
    /// # Safety
    ///
    /// The caller must ensure the bit pattern of `Self` is a valid
    /// instance of the target at every byte the two types share.
    ///
    /// Size equality is guaranteed by the [`SizedWithState`] bound, and
    /// rechecked bu [`TransmutableState::LAYOUT_CHECK`].
    unsafe fn transmute_state<To: State>(self) -> Self::Target
    where
        Self: TransmutableState<To, SIZE, ALIGN>,
    {
        const { Self::LAYOUT_CHECK }
        let value = core::mem::ManuallyDrop::new(self);
        // SAFETY: `Self` and `Target` are the same struct with only thier
        // state changed.
        unsafe { core::mem::transmute_copy::<Self, Self::Target>(&*value) }
    }

    /// Bit-reinterprets `&self` as a reference to the same container type
    /// with the [`State`] `To` plugged in.
    ///
    /// # Safety
    ///
    /// The caller must ensure the bit pattern of `Self` is a valid
    /// instance of the target at every byte the two types share.
    ///
    /// Size and Alignment equality is guaranteed by the [`SizedWithState`]
    /// bound, and rechecked bu [`TransmutableState::LAYOUT_CHECK`].
    unsafe fn transmute_state_ref<To: State>(&self) -> &Self::Target
    where
        Self: TransmutableState<To, SIZE, ALIGN>,
    {
        const { Self::LAYOUT_CHECK }
        unsafe { &*(self as *const Self as *const Self::Target) }
    }

    /// Bit-reinterprets `&mut self` as a mutable reference to the same
    /// container type with the [`State`] `To` plugged in.
    ///
    /// # Safety
    ///
    /// The caller must ensure the bit pattern of `Self` is a valid
    /// instance of the target at every byte the two types share.
    ///
    /// Size and Alignment equality is guaranteed by the [`SizedWithState`]
    /// bound, and rechecked bu [`TransmutableState::LAYOUT_CHECK`].
    unsafe fn transmute_state_mut<To: State>(
        &mut self,
    ) -> &mut Self::Target
    where
        Self: TransmutableState<To, SIZE, ALIGN>,
    {
        const { Self::LAYOUT_CHECK }
        unsafe { &mut *(self as *mut Self as *mut Self::Target) }
    }
}

impl<T: WithState, const SIZE: usize, const ALIGN: usize>
    TransmuteState<SIZE, ALIGN> for T
{
}

/// Converts a wrapper around one state's projection into the same wrapper
/// around another's.
///
/// `#[typestate]` sees through `Option`, arrays, `Box` and tuples by
/// itself. Any other type that mentions the state - a user wrapper such as
/// `Pair<S::Value>` - is opaque to it, so the generated `restate_with`
/// method hands the value to this trait instead. `f` converts one bare
/// projection; the impl decides where inside `Self` to apply it:
///
/// ```ignore
/// impl<A, B> Restate<A, B> for Pair<A> {
///     type Output = Pair<B>;
///     fn restate(self, f: &mut impl FnMut(A) -> B) -> Pair<B> {
///         Pair(f(self.0), f(self.1))
///     }
/// }
/// ```
///
/// The impl must be generic over both projections like the one above: the
/// generated method requires
/// `Pair<S::Value>: Restate<S::Value, S2::Value, Output =
/// Pair<S2::Value>>` for every target state `S2`, and the missing impl
/// surfaces as an ordinary trait-bound error where `restate_with` is
/// called.
///
/// There is deliberately no blanket impl for the bare projection itself:
/// coherence would reject it next to the impls for `Option<T>` and
/// friends, which is why those shapes are expanded by the macro instead.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is not a wrapper `#[typestate]` can restate",
    note = "`#[typestate]` sees through `Option`, arrays, `Box` and \
            tuples; for any other wrapper around a projection, implement \
            `groupoid::Restate` for it"
)]
pub trait Restate<Src, Dst> {
    /// `Self` with `Dst` in place of every `Src`.
    type Output;

    /// Rebuilds `self` for the target state, converting each projection
    /// with `f`.
    fn restate(self, f: &mut impl FnMut(Src) -> Dst) -> Self::Output;
}
